---
kind: Secret
apiVersion: v1
metadata:
  name: example-annotation
  annotations:
    awssecretmanager.kubernetes.io/enabled: "true"
type: Opaque
data:
  username: <username>
  password: <password>
---